config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'users/new'

  get 'users/edit'

  get 'welcome/index'

  
  resources :articles do
    resources :comments
  end

  resources :users

  resources :user_sessions

  root 'welcome#index'

  get "update_user" => "users#edit", :as => "update_user"

  get "users_index" => "users#index", :as => "users_index"

  get "logout" => "user_sessions#destroy", :as => "logout"

  get "login" => "user_sessions#new", :as => "login"

  get "sign_up" => "users#new", :as => "sign_up"

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :email, :password, :password_confirmation
  # attr_reader :password_hash
  # has_many :roles, :through => :assignments
  
  # before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email


  # ROLES = %w[admin moderator author]

  # def role_symbols
  #   roles.map do |role|
  #     role.name.underscore.to_sym
  #   end
  # end


  # def encrypt_password
  #   if password.present?
  #     self.password_salt = BCrypt::Engine.generate_salt
  #     self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  #   end
  # end
end

app/models/user_session.rb
class UserSession < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # helper :all

  # protect_from_forgery with: :exception

  helper_method :current_user

  def current_user_session
  	return @current_user_session if defined?(@current_user_session)
  	@current_user_session = UserSession.find
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def validate_user
  	# unless current_user means "unless @current_user == true"
  	unless current_user
  		flash[:notice] = "Must be a registered user!"
  		redirect_to :log_in
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	http_basic_authenticate_with name: "sam", password: "12345", except: [:index, :show]
	
	def new
		@article = Article.new
	end
  
  # create
	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	# read
	def show
		@article = Article.find(params[:id])
	end

	def index
		@articles = Article.order('created_at DESC')
	end

	def edit 
		@article = Article.find(params[:id])
	end

	# update
	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else 
			render 'edit'
		end
	end

	# destroy
	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  	@user_session = UserSession.new
  end

  def create
  	@user_session = UserSession.new(params[:user_session])
  	if @user_session.save
  		flash[:notice] = "Successfully logged in."
  		redirect_to root_url
  	else
  		render :action => 'new'
  	end
  end

	def destroy
  	user_session[:user_id] = nil
  	redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
# the Users controller

class UsersController < ApplicationController
  # GET /users

  def new
    @user = User.new
  end

  def create
    # params gathers them into a hash
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else 
      render "new", alert: 'User could not be created'
    end
  end

  def edit 
    @user = User.find(user_params[:user_id])
  end

  # GET /users
  def index
    @users = User.all
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back to Articles', articles_path %>

app/views/articles/index.html.erb
<center><h2>Esteemed writings</h2></center>

<%= link_to "New article", new_article_path %>

<table>
  <tr>

    <th colspan="3"></th>
  </tr>
 
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= simple_format article.text %></td>
    <td><%= link_to "Show", article_path(article) %></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Delete", article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back to Articles', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Remove Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!-- new user form -->
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<!-- tells you who is logged in -->

<div id="user_nav">

  <% if current_user %>
    Logged in as <%= current_user.email %>
    
  <br>
    <%= link_to "Log out", logout_path %>
  </br>

  
  <% else %>
    <%= link_to "Sign Up", sign_up_path %> or
    <%= link_to "Log In", login_path %>
  <br>
    <%= link_to "Home", root_path %>
  </br>
  <% end %>
</div>


<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

</body>
</html>

app/views/user_sessions/new.html.erb
<h1>Log in</h1>

<%= form_tag user_sessions_path do %>
  <p>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p class="button"><%= submit_tag "Log in" %></p>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email, "Email Address" %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </p>


  <p><%= f.submit "Sign up" %></p>

<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Registered Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
    </tr>
  </thead>

  <tbody>
	<% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
		  </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to "Home", root_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h2>Sam's Rails Adventure</h2>
<%= link_to 'My Blog', controller: 'articles' %><br>
<%= link_to 'Users Index', users_index_path %>